sudo: required
services:
    - docker

before_install:
    - docker build -t pjcubero/docker-react -f Dockerfile.dev .     

script:
    - docker run -e CI=true pjcubero/docker-react npm run test     

